baseurl = "/"
languageCode = "en-us"
title = "Remolques y Servicios"

# Navigation
[params.navigation]
brand = "Remolques y Servicios"

[params.navigation.links]
about     = "About"
services  = "Services"
portfolio = "Portfolio"
contact   = "Contact"


# Hero section
[params.hero]
# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
slogan     = "Remolques y Servicios"
subtitle   = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis nesciunt consequatur ut nihil voluptatem fugiat eos eveniet alias in veniam?"
buttonText = "Find out more"


# About section
[params.about]
headline    = "We've got what you need!"
description = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Praesentium similique eos eligendi error veritatis harum, sed aliquid totam, quam minus neque enim est architecto, ad. Maiores, aliquid, vitae!"
buttonText  = "Get started!"

# Service section
[params.services]
headline = "At your service"

[[params.services.remolque]]
icon = "fa-diamond"
title = "Remolques"
description = "Remolque bla bla bla."

[[params.services.enganches]]
icon = "fa-diamond"
title = "Enganches (Hitch)"
description = "Enganches bla bla bla."

[[params.services.grua]]
icon = "fa-diamond"
title = "Grua para Motos"
description = "Grua bla bla bla."

# Portfolio modals
[params.portfolio.modal]
client = "Client"
date = "Date"
category = "Category"
buttonText = "Close"

# Aside section
[params.aside]
headline = "Get the Creative Theme for Hugo"

[params.aside.button]
text = "Download now"
link = "//github.com/digitalcraftsman/hugo-creative-theme"

# Contact section
[params.contact]
headline = "Let's Get In Touch!"
description = "Call us"
phone = "123-456-6789"
email = "feedback@demoapp.com"
