baseurl = "/"
languageCode = "en-us"
title = "Remolques y Servicios"

[[params.services.remolque]]
icon = "fa-diamond"
title = "Remolques"
description = "Remolque bla bla bla."

[[params.services.enganches]]
icon = "fa-diamond"
title = "Enganches (Hitch)"
description = "Enganches bla bla bla."

[[params.services.grua]]
icon = "fa-diamond"
title = "Grua para Motos"
description = "Grua bla bla bla."


